### ISSUE TITLE
对模板做任何修改，[校验]时都会提示,校验配置失败 配置不合法: undefined

### ISSUE THREAD

**Issue by myfingerhurt** [cntechpower/v2ray-webui#23]
比如把warning改为info不允许，
v2ray_error.log改名可以，但改路径不允许。
文本其他地方基本不能改，比如我想配置quic模式，但是一个字段都不能动。
···
    error: 'v2ray_error.log',
    loglevel: 'warning',
    access: 'v2ray_access.log'
···

**Comment by cntechpower** [comment]
已复现, 修改配置后. 没有正确获取到配置内容. 提交了空配置. 
正在排查原因
![image](https://user-images.githubusercontent.com/20899726/111033726-a0cbef80-844d-11eb-9b73-74ffb5eea79b.png)

**Comment by cntechpower** [comment]
@myfingerhurt 
Hi, 问题已在最新版本修复,  可参照readme中的升级步骤升级后查看问题是否仍存在. 

仍存在可reopen此issue. 感谢
